name: lfr

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.15.2
  - ipython=8.7.0
  - matplotlib=3.6.2
  - pandas=1.5.2
  - scikit-learn=1.1.3
  - pytorch-cuda=11.7
  - python=3.10.8
  - pytorch>=1.13
  - torchvision=0.14.1
  - pillow=9.3.0
  - pip=22.3.1
  - tqdm=4.64.1
